### ISSUE TITLE
Attribute Selectors

### ISSUE THREAD

**Issue by ctidd** [devlint/gridlex#1]
[attr*=value] selectors for class names in this context are likely to have unintended consequences, particularly with such short class values and no namespacing. (Imagine classes such as collapse or color.)

Sticking with the approach of loose-matching selectors, the col selector looks like it could be more safely expressed as `.col, [class*="col-"]` without breaking compatibility. What do you think of this?

**Comment by devlint** [comment]
You're right! 
I'm just working on it to protect that.
Thank you

**Comment by devlint** [comment]
Fixed, thx for your comment!

**Comment by ctidd** [comment]
Awesome, thanks!
