### ISSUE TITLE
[Feature Request] Variable Class Name Prefix

### ISSUE THREAD

**Issue by timothyallan** [devlint/gridlex#18]
Great work on the library! 

It's making my life much easier, except that I've run into a snag with conflicting CSS names, primarily with the generic "grid" class. I've got a few other libraries which unfortunately also use that name, and it's causing chaos.

Allowing Gridlex to use a class prefix variable would clear off class name re-use issues forever! i.e. gl_grid, gl_col etc...

**Comment by devlint** [comment]
`.grid` and `.col` are now variables. You can change them in gridlex-vars : 
@gl-gridName/$gl-gridName and @gl-colName/$gl-colName
