### ISSUE TITLE
col-0?

### ISSUE THREAD

**Issue by sconstantinides** [devlint/gridlex#21]
What are your thoughts on adding col-0 classes? These would function as utility classes to hide columns at various breakpoints.

For example, a sidebar may look like "col-2_md-3_sm-0" to indicate that it should be hidden on mobile.

I'm happy to submit a PR if this is something others would find useful.

PS- This grid seriously rocks. Thanks!

**Comment by devlint** [comment]
For a recent project, I've enhanced Gridlex with this:
```
@media @gl-lg{
  [class*='grid'] > [class*="_lg-0"]{display: none;}
  [class*='grid'] > [class*="_lg-first"]{order: -1;}
  [class*='grid'] > [class*="_lg-last"]{order: 1;}
}
@media @gl-md{
  [class*='grid'] > [class*="_md-0"]{display: none;}
  [class*='grid'] > [class*="_md-first"]{order: -1;}
  [class*='grid'] > [class*="_md-last"]{order: 1;}
}
@media @gl-sm{
  [class*='grid'] > [class*="_sm-0"]{display: none;}
  [class*='grid'] > [class*="_sm-first"]{order: -1;}
  [class*='grid'] > [class*="_sm-last"]{order: 1;}
}
@media @gl-xs{
  [class*='grid'] > [class*="_xs-0"]{display: none;}
  [class*='grid'] > [class*="_xs-first"]{order: -1;}
  [class*='grid'] > [class*="_xs-last"]{order: 1;}
}
```

Maybe it's time to add them in next release?

You are welcome to submit a PR by adding col-0 to less/sass files and document them :)
