### ISSUE TITLE
What happened to the dist folder?

### ISSUE THREAD

**Issue by bensampaio** [devlint/gridlex#22]
On version 2.2 the dist folder is no longer present. Any reason for that? Since there are bugs on the SASS version (#16) I would like to still be able to use the compiled files while those bugs aren't fixed. I know the CDN version is also there but I don't want to be dependent on it.

Could this change be reverted? Thanks!

**Comment by devlint** [comment]
Hello, 
Since the change in method of publishing gh-pages from Github, I modify `dist/` folder to `docs/`.
All the source files and generate files are in the same places.
Is it ok for you?
Can you try again #16 issue please?

**Comment by bensampaio** [comment]
Oh ok, I didn't notice the files were still there but under the `docs/` folder instead.

In my opinion, the `gridlex.css` and `gridlex.min.css` should still be in the `dist/` folder, since that would be consistent with several other projects. But as long as they are there I'm fine with the approach.

I will check the other issue.
