### ISSUE TITLE
Supporting stylus

### ISSUE THREAD

**Issue by Emmanuel-Italic** [devlint/gridlex#31]
Hi,

Do you plan to support stylus, in addition to less and sass? It's always the left-behind one…

Thanks!

**Comment by devlint** [comment]
Hello @Emmanuel-Italic 
No, unfortunately I have no idea about Stylus :(
I know there are some sass (or less) compilers to stylus, and if someone wants to make a fork of Gridlex in Stylus, it's opened!
_it's already difficult to maintain two preprocessors... so one more..._

**Comment by EmmanuelBeziat** [comment]
Okay, I’ll try to make a fork then.
