### ISSUE TITLE
.col-first and .col-last with breakpoints

### ISSUE THREAD

**Issue by edoher** [devlint/gridlex#38]
Hi,
The grid is fantastic and very flexible, we love it! Unfortunately, there are no breakpoints for REVERSE, FIRST or LAST. That means that if, for example, I need columns to go side-by-side on desktop, but one over the other (in REVERSE order) on mobile, I cannot do it :(

Could you please integrate thos enice xs, sm, md breakpoints for these classes as well?

Thanks!

**Comment by devlint** [comment]
Done in new 2.3.7 release
You can now have `<div class="col_xs-last_md-first">` for example
https://github.com/devlint/gridlex/releases/tag/2.3.7
