### ISSUE TITLE
Elements inside cols displaying incorrectly. 

### ISSUE THREAD

**Issue by tinamayswinkels** [devlint/gridlex#39]
Having an issue where elements placed inside the divs with a class of col also appear in columns themselves. For example, 
      <div class="col">
      <h2> Heading </h2>
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque vestibulum dapibus felis, sed convallis turpis aliquam nec. </p>
    </div>

Displays like this with the heading and the paragraph next to each other. 
![screen shot 2016-12-09 at 5 48 51 pm](https://cloud.githubusercontent.com/assets/10876260/21040243/cab8e6c6-be37-11e6-91bc-f3f2adf54375.png)

I understand I could probably fix this by adding an additional div, but I would rather not add unnecessary markup if I can avoid it.

**Comment by TheKidCoder** [comment]
Could you post an example of your markup?

**Comment by tinamayswinkels** [comment]
closed in separate thread.
