### ISSUE TITLE
How to hide content for greater than lg (1280px)?

### ISSUE THREAD

**Issue by animeshchat** [devlint/gridlex#40]
There doesn't seem to be a way to hide content for greater than 1280px / 'lg' (see below). Is there a way that I'm missing? Or should I add my local overrides?

.col
  -* (1 to 12)
  _xs-* (0 to 12)
  _sm-* (0 to 12)
  _md-* (0 to 12)
  _lg-* (0 to 12)
    e.g. <div class="col-12_lg-8_md-6_sm-3_xs-1">...</div>

// Added the following locally to get it to work 

$gl-xl:        "screen and (min-width: 80em)" !default; // max 1280px

@media #{$gl-xl}{
  @include makeGridByNumber(_xl);
}

@media #{$gl-xl}{
  @include makeCol(_xl);
  @include makeOff(_xl);
}

@media #{$gl-xl}{
  [class*="#{$gl-gridName}"] {
    > :not([class*="_xl-0"]){
      display: block;
    }
    &:not([class*="_xl-0"]) {
      display: flex;
    }
    >[class*="_xl-0"],
    &[class*="-equalHeight"] > [class*="_xl-0"]{
      display: none;
    }
  }
}

**Comment by scrwdnet** [comment]
I believe there is a 'hidden' size of xl which is your first number after a 'col' so `col-0` would be hidden on xl. So you can do `col-0_lg-6_md-3`. That's what I'm doing anyway.

**Comment by devlint** [comment]
Hello, 
@scrwdnet is right.
`col-0` hides the column whatever the mediaqueries. So you can have `col-0_lg-12` to show 1 cell from 0 to 1280px, but hide it after 1280px.
Thanx @scrwdnet!
