### ISSUE TITLE
Possible to use through sass as @include?

### ISSUE THREAD

**Issue by adrianocr** [devlint/gridlex#41]
Foundation 6 does this thing where in your sass files you can go `@include grid-column(6)` (for 6 columns, but any number from 1-12 is valid) and it generates the styles for you in whatever block you want. 

Useful for keeping your classes clean. 

Use as so:

    .wrapper {
        @include grid-row();
    }

    .main-block {
        @inclide grid-column(8);
    }

    .sidebar {
        @include grid-column(4);
    }

Is there any to use gridlex as such? 

Foundation way: http://foundation.zurb.com/sites/docs/grid.html

**Comment by devlint** [comment]
Hello,
This is not planned at the moment
