### ISSUE TITLE
Display div in spaceBetween 

### ISSUE THREAD

**Issue by alasomic** [devlint/gridlex#42]
Hi Guy's, 
sorry for my english ...
So i'm trying to explain,  i have 2 columns :

```
<div class="col-8_sm-12"></div>
<div class="col-4_sm-12 grid">
     <div id="one" class="col-12_sm-6_xs-12"></div>
     <div id="two" class="col-12_sm-6_xs-12"<div>
     <div id="three" class="col-12_sm-6_xs-12"></div>
</div>
```

The problem is that my blocks "one" "two" and "three" are displayed like there was a "spaceBetween" and i don't know why . I would like block displaying like a "flex-start" but how i can do that ? 

Thanks

**Comment by devlint** [comment]
Hello @alasomic 
Can you put some screenshot, because I don't understand what is the problem! 
Thx

**Comment by devlint** [comment]
Hello, 
is it because there is a typo in the code?
```<div class="col-8_sm-12"></div>
<div class="col-4_sm-12 grid">
     <div id="one" class="col-12_sm-6_xs-12"></div>
     <div id="two" class="col-12_sm-6_xs-12"<div> <!-- the div#two is not closed -->
     <div id="three" class="col-12_sm-6_xs-12"></div>
</div>```
