### ISSUE TITLE
children of equal height columns become columns themselves

### ISSUE THREAD

**Issue by tinamayswinkels** [devlint/gridlex#43]
I'm experiencing a bug where children of columns inside an equal height grid become columns themselves. I've written some hacky code to override it, but seems like an un-intended behaviour. Appears in both safari and chrome, so I don't think it's a browser issue. 

http://codepen.io/instituteofcode/pen/dNBbvw

<img width="1273" alt="screen shot 2017-02-19 at 12 06 04 pm" src="https://cloud.githubusercontent.com/assets/10876260/23099186/dd8de912-f69b-11e6-9ae2-5bb83c66a013.png">

**Comment by devlint** [comment]
See https://github.com/devlint/gridlex/commit/fde3d54dc1da2d5c46a5e3adbbdaee86d45b2a1b
---
New release fixing the issue : 2.2.5 (https://github.com/devlint/gridlex/releases/tag/2.2.5)

Ok for you?
Thx

**Comment by tinamayswinkels** [comment]
Thanks!
