### ISSUE TITLE
Bottom gap issue with nested grids.

### ISSUE THREAD

**Issue by didacus** [devlint/gridlex#45]
I am having a problem adding an `img` tag inside a nested grid. For some reason it creates a gap at the bottom that I can't remove.

[Screenshot](https://cl.ly/0d3f1U3W2t32)
 
HTML
```
  <div class="grid-noGutter">
    <div class="col-12 grid-noGutter">
      <div class="col-8" data-push-left="off-2">
        <img class="imgContent" src="../img/santander/participant-md.png" alt="">
      </div>
    </div>
  </div>
```

CSS
```
.imgContent {
  width: 100%;
  height: auto;
  image-rendering: auto;
  background-color: $gray;
}
```

**Comment by devlint** [comment]
Hello, 
did you try to put `display: block;` to your picture? An `<img>` element, by default, is inline, and a space after can be visible.
Thanks for the issue.

**Comment by didacus** [comment]
Perfect, it did work. Like you mention the `display: block;` was missing. Thank you for your help @devlint

**Comment by devlint** [comment]
You're welcome :)
