### ISSUE TITLE
NPM version 2.3.0 ships incorrect docs/gridlex.css file

### ISSUE THREAD

**Issue by Cherry** [devlint/gridlex#50]
With the latest NPM version, the `docs/gridlex.css file` (as well as the minified version) appears to be using the `gridlex` selector, rather than the `class` selector by default. As per commit https://github.com/devlint/gridlex/commit/6c5b5cd637d98d06831331ec1e1d6c1d9292df98 I assume this is not intentional?

Thanks!

**Comment by devlint** [comment]
Hi @Cherry!
Thank you for the issue. Yes, my bad, it is not intentional :(
This is know fix, with version 2.3.1.
sorry for the inconvenience!
