### ISSUE TITLE
Unexpected "starts with" col class selector

### ISSUE THREAD

**Issue by Cherry** [devlint/gridlex#51]
The following screenshot has the latest version on the left, with the older version on the right:

https://jross.me/l/v836m

As you can see, all of the classes on the left use a starts with operator, which triggers unexpected styling on classes such as `colorBand`, etc. This also causes another issue with elements that have `col` as a class, but not the first class. For example, using `someClass col` inside of a `grid-6` won't trigger the latest rule in 2.3.1 as it does not start with `col`. 

Is this intended behaviour, or a regression from the previous version?

**Comment by Cherry** [comment]
This looks to have been caused by https://github.com/devlint/gridlex/commit/180bc6639a44f88d3bfdcb7da9863a27802c8c64#diff-0be8c604249748f90aea17a7a44878d3L125

**Comment by devlint** [comment]
Thank you for the issue @Cherry !!
This is now fix in the new version 2.3.4.
