### ISSUE TITLE
@media queries - min-width

### ISSUE THREAD

**Issue by IrvingArmenta** [devlint/gridlex#52]
## Hola!
It's a great framework, I'm thinking in using it, however, is there a way to set up the media queries to work with a "mobile first" mindset? 

This is kind of the mindset I'm talking about: [css-media-queries-best-practices](https://gist.github.com/basham/3b24062dfaecaa712a68)

I tried to just change media queries to min-width values, but the way the classes are set up makes the layout to not work as it should be ( stacking up columns in smaller devices - more space for content );

Hopefully I'm making sense; min-width is better for general performance as mobile devices doesn't have the graphic "power" of larger devices, that is basically the idea.  

Thanks a lot!

**Comment by devlint** [comment]
Hola!
Gridlex is not based in mobile-first stylen sorry.... 
But yes it is better to be mobile-first :) 

Maybe in the next big release, as v3 ?!
