### ISSUE TITLE
Clearfix

### ISSUE THREAD

**Issue by didacus** [devlint/gridlex#54]
How can I solve Clearfix issues with Gridlex? I've tried the solution below without success.

Thank you in advance.

```
.cf:before,
.container:after {
  content: "";
  display: table;
}

.cf:after {
  clear: both;
}
/* IE 6/7 */
.cf {
  zoom: 1;
}

**Comment by devlint** [comment]
Threre is no "clearfix" solution for flexbox... Have you tried to use `data-push-right` with the desired value on the "last" col of the line 
See http://gridlex.devlint.fr/#documentation
