### ISSUE TITLE
Appears bottom scroll

### ISSUE THREAD

**Issue by slavikse** [devlint/gridlex#6]
Appears while using the bottom scroll normalize.css. If you set the margin to the default value (8px), the scroll disappears.
ps: abolish the right margin at grid- *, scroll disappears.

**Comment by borantula** [comment]
+1

**Comment by devlint** [comment]
Hello, 
Can you be more precise? Have you an example that I can see to fix it? 
Thx!

**Comment by borantula** [comment]
Of course :) I used it building my new homepage this week (thanks by the way). 
Here are two versions
* Gridlex Overwritten: http://borayalcin.me/
* Unchanged: http://bora.com/byme/gridlex-scroll.html

You can see it by making the screen width smaller than content. You'll see a few pixels of overflow-x and scrollbar on the second one. To prevent it I removed margin from [class*="grid"] .

Hope it helps

**Comment by devlint** [comment]
Hello, 
this isn't really an issue: Gridlex works by default with gutters. And gutters are apply on the right and the left of each cols, so the `grid` needs to have negative-margins both sides (left and right).

In your page, there are 2 possibilities:
1st: add a padding on left and right egal to the gutters value (.5em by default) to your container
`.site-content{... padding: 0 .5em; ...}`
The advantage is that the content is not glued to the edges of the window.

2nd: use -noGutter on the grid:
`<div class="grid-noGutter">`

Hope this helps you.
