### ISSUE TITLE
Is it possible to animate the grids on change? 

### ISSUE THREAD

**Issue by daniel-farina** [devlint/gridlex#66]
Hi Guys,

Is it possible to animate columns with something like such? 

```
     -webkit-transition:flex  300ms ease-in-out!important;
     -moz-transition:flex  300ms ease-in-out!important;
     -o-transition:flex  300ms ease-in-out!important;
     transition:flex  300ms ease-in-out!important;
```

I tried different methods without success.  I even tried applying that to all divs on my page but the flex boxes do not animate. 

Thank you

**Comment by devlint** [comment]
Because of max-width, you need to transition flex-basis & max-width properties : 
```transition: flex-basis 300ms ease-in-out,max-width 300ms ease-in-out```

Does it work for you?
