### ISSUE TITLE
Hiding columns

### ISSUE THREAD

**Issue by Cherry** [devlint/gridlex#69]
As per the documentation at http://gridlex.devlint.fr/:

> Columns can be hidden at breakpoints using _*-0 (e.g. col-4_md-6_sm-0)

However, this appears to have changed to require using `-hidden` in the latest version. Is this an intentional change, and if so, can the documentation be updated please?

**Comment by devlint** [comment]
Thank you James!

Yes, this is a new change. 
And the doc is now updated.

**Comment by Cherry** [comment]
Thanks. Wouldn't it make more sense, when pushing a breaking change like this, to bump the version a little higher to follow SemVer? A lot of people rely on "compatible with" or other similar version ranges in their `package.json` and this broke our build unsuspectingly until we analysed the changes.

**Comment by devlint** [comment]
Yes, you're right. 
Version 2.4.2/2.4.3 are deleted.
Version 2.5.0 is now the last version.

**Comment by Cherry** [comment]
Thanks! 👍
