### ISSUE TITLE
Customize CSS class name

### ISSUE THREAD

**Issue by waghcwb** [devlint/gridlex#79]
Some projects follow some rules to writing CSS class names, like `PascalCase`, `camelCase`, `snake_case` or `kebab-case`.

But when using this framework I cannot customize the class name (eg: grid-spaceBetween)

I want to customize the class name and use `grid-spaceBetween`, `grid-space-between`, or `whatever`

**Comment by TheKidCoder** [comment]
This should be completely possible by changing the SCSS variables to whatever you would like and compiling.

**Comment by waghcwb** [comment]
@TheKidCoder,

Thank you. I noticed that I can change these vars in `gridlex-vars.scss` file
`$gl-gridName:   grid !default;`
`$gl-colName:   col !default;`
`$gl-attributeName: class !default;`
